# Generated by Django 6.0.5 on 2026-06-01 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=600)),
                ('city', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Pokhara', 'Pokhara'), ('Butwal', 'Butwal'), ('Chitwan', 'Chitwan'), ('Biratnagar', 'Biratnagar'), ('Birgunj', 'Birgunj'), ('Other', 'Other')], max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('rent', models.PositiveIntegerField(help_text='Monthly rent in NPR')),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('shared', 'Shared Room'), ('flat', 'Whole Flat'), ('pg', 'PG / Hostel')], max_length=10)),
                ('gender_pref', models.CharField(choices=[('M', 'Male Only'), ('F', 'Female Only'), ('A', 'Any Gender')], default='A', max_length=1)),
                ('available_from', models.DateField()),
                ('furnished', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('water_included', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='e.g. 27.7172', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='e.g. 85.3240', max_digits=9, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listing_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
